.\" Copyright (C) 2026 TheCRatTime
.\"
.\" Licensed under the Apache License, Version 2.0 (the "License");
.\" you may not use this file except in compliance with the License.
.\" You may obtain a copy of the License at
.\"
.\"     http://www.apache.org/licenses/LICENSE-2.0
.\"
.\" Unless required by applicable law or agreed to in writing, software
.\" distributed under the License is distributed on an "AS IS" BASIS,
.\" WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
.\" See the License for the specific language governing permissions and
.\" limitations under the License.
.TH "ArenaAlloc" "3" "2026\-10\-07" "arena" "Arena Manuals"
.SH NAME
\fBArenaAlloc\fR \- allocate bytes in arena.\&
.PP
.SH SYNOPSIS
.nf
\fB#include "arena.\&h"\fR
.fi
.PP
.nf
\fBvoid* ArenaAlloc(Arena* \fIarena\fB, size_t \fIbytes\fB);\fR
.fi
.PP
.SH DESCRIPTION
\fBArenaAlloc\fR allocates \fIbytes\fR bytes from \fIarena\fR.\&
.PP
\fIarena\fR
.RS 4
Pointer to \fBArena\fR struct.\&
.RE
.PP
\fIbytes\fR
.RS 4
Bytes of data.\&
.RE
.PP
.SH RETURN VALUE
Return value is pointer to data or \fBNULL\fR if haven't memory in arena.\&
.PP
.SH AUTHORS
Project and man\-page: TheCRatTime.\&
.PP
.SH SEE ALSO
\fBArenaReset\fR(3), \fBInitArena\fR(3), \fBArena\fR(3type)
