.TH README 1 2026\-10\-07 TheCRatTime arena
.SH arena
\fBarena\fR \- allocate memory and free memory once.\&
.P)
.SH Description
This is \fBSingle\-header\fR library with fast memory arena.\&
You need allocate memory and free it once.\&
.PP
.SS Features
\fB\-\fR ANSI C/C89 code standard.\&
.br
\fB\-\fR Single\-header library.\&
.br
\fB\-\fR Out\-Of\-Bounds detection.\&
.br
\fB\-\fR Compiles with \fB\-Weverything \-pedantic \-Werror \-Wno\-unsafe\-buffer\-usage \-Wno\-old\-style\-cast\fR flags.
.PP
.SS Quick start
.nf
.RS 4
#define ARENA_SOURCE
/* Without debug information */
#define FAST_ARENA

/* Using BIND */
#define NEEDED_BIND
#include ".\&.\&/include/arena.\&h"

#include <stdio.\&h>

/* Generate BIND with ID '\&ex'\& */
GEN_BIND(ex);

int main(void) {
  Arena* example = InitArena(4096);
  int* data1 = NULL;
  int* data2 = NULL;
  
  if (example == NULL) {
    printf("Out of memory\en");
    return 1;
  }

  /* Using BIND */
  BindIDex(example);

  /* This is C++ style.\& */
  /* Can allocate so: */
  data1 = example->Alloc(sizeof(int));
  data2 = example->Alloc(sizeof(int));

  if (data1 == NULL || data2 == NULL) {
    /* Need only free arena.\& */
    FreeArena(example);
    printf("Arena allocate failed\en");
    return 1;
  }

  *data1 = 5;
  *data2 = 50;
  
  printf("%d + %d = %d\en", *data1, *data2, (*data1 + *data2));

  /* You only free arena */
  FreeArena(example);
  return 0;
}
.fi
.RE
.PP
.SS Building
.nf
.RS 4
cmake \-B build
cd build/
make
.fi
.RE
.PP
.SS Authors
TheCRatTime.\&
.PP
.SS Examples
You can see examples in \fBexamples/\fR directory.\&
.PP
.SS License
Project is under Apache 2.0 license.\&
.PP
.SS Also
See this README.\&md in manual \-> \fBREADME.\&1\fR with
this command:
.PP
.nf
.RS 4
man \-l README.1
.fi
.RE
.PP
